name: Generate image

on:
  push:
    branches:
      - master

jobs:
  generate-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt

      - name: Generate image
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          python generate_image.py
